services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=nexus_wms'
      - 'POSTGRES_PASSWORD=nexus123'
      - 'POSTGRES_USER=nexus'
    ports:
      - '5432:5432'
    volumes:
      - nexus_pgdata:/var/lib/postgresql/data

volumes:
  nexus_pgdata:
